project:
  type: website
  resources:
    - data  # Include data folder in built site

date: last-modified

author: 
  - name: Christoph Kovacs
    
execute:
  freeze: auto

website:
  title: "The Kodonian Project"
  repo-url: https://github.com/kodonian/kodonian.github.io
  repo-actions: [source]
  bread-crumbs: true
  
  sidebar:
    style: "docked"
    contents: auto
  page-footer:
    center: 
      - text: "Pub: May 25, 2025 â€“ Upd: {{< meta date >}}."
      

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    grid:
      margin-width: 350px
      
bibliography: refs/references.bib
link-citations: true
      
reference-location: margin
citation-location: margin
fig-cap-location: margin
tbl-cap-location: margin